# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyguide',
            name='name',
            field=models.CharField(max_length=32, unique=False),
        ),
        migrations.AlterUniqueTogether(
            name='studyguide',
            unique_together=set([('name', 'owner')]),
        ),
    ]
